import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/layouts/header/Header";
import Footer from "@/components/layouts/footer/Footer";
import SessionWrapper from "@/components/sessionWrapper/SessionWrapper";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "car showcase app ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script src="https://cdn.lordicon.com/lordicon.js"></script>
        <StoreProvider>
          <SessionWrapper>
            <Header />
            {children}
            <Footer />
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
